M48
; DRILL file {KiCad (6.0.0)} date Fri Jan 14 16:12:00 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-14T16:12:00-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X104.845Y-85.09
X105.86Y-80.01
X106.875Y-85.09
T2
X112.6Y-49.9
X112.7Y-85.1
T0
M30
